INSERT INTO users (username, password) VALUES ('nisi.a','53647710499');
INSERT INTO users (username, password) VALUES ('odio','18491820599');
INSERT INTO users (username, password) VALUES ('et.ultric','88554391499');

INSERT INTO agents (name, divisionId) VALUES ('Tarik Sampson',14);
INSERT INTO agents (name, divisionId) VALUES ('Gil Berg',16);
INSERT INTO agents (name, divisionId) VALUES ('Lane Foreman',5);
INSERT INTO agents (name, divisionId) VALUES ('Joseph Adkins',20);
INSERT INTO agents (name, divisionId) VALUES ('Colorado Mcpherson',2);
INSERT INTO agents (name, divisionId) VALUES ('Warren Rodgers',5);
INSERT INTO agents (name, divisionId) VALUES ('Neil Kirkland',2);
INSERT INTO agents (name, divisionId) VALUES ('Kelly Cobb',12);
INSERT INTO agents (name, divisionId) VALUES ('Ali Hewitt',6);
INSERT INTO agents (name, divisionId) VALUES ('Sean Warner',8);
INSERT INTO agents (name, divisionId) VALUES ('Marvin Lowe',8);
INSERT INTO agents (name, divisionId) VALUES ('Noah Oconnor',11);
INSERT INTO agents (name, divisionId) VALUES ('Kaseem Rivers',3);
INSERT INTO agents (name, divisionId) VALUES ('Octavius Haney',4);
INSERT INTO agents (name, divisionId) VALUES ('Alexander Kramer',11);
INSERT INTO agents (name, divisionId) VALUES ('Nash Bishop',18);
INSERT INTO agents (name, divisionId) VALUES ('Damian Summers',10);
INSERT INTO agents (name, divisionId) VALUES ('Arden Burgess',18);
INSERT INTO agents (name, divisionId) VALUES ('Hakeem Franks',16);
INSERT INTO agents (name, divisionId) VALUES ('Macaulay Holman',7);
INSERT INTO agents (name, divisionId) VALUES ('Connor Robbins',20);
INSERT INTO agents (name, divisionId) VALUES ('Thor Trujillo',6);
INSERT INTO agents (name, divisionId) VALUES ('Burke White',17);
INSERT INTO agents (name, divisionId) VALUES ('Jordan Moses',8);
INSERT INTO agents (name, divisionId) VALUES ('Harlan Villarreal',10);
INSERT INTO agents (name, divisionId) VALUES ('Alden Riggs',3);
INSERT INTO agents (name, divisionId) VALUES ('Ashton Cross',17);
INSERT INTO agents (name, divisionId) VALUES ('Leroy Wall',6);
INSERT INTO agents (name, divisionId) VALUES ('Tad Young',14);
INSERT INTO agents (name, divisionId) VALUES ('Herrod Holcomb',19);
INSERT INTO agents (name, divisionId) VALUES ('Fitzgerald Spencer',18);
INSERT INTO agents (name, divisionId) VALUES ('Blaze Jarvis',11);
INSERT INTO agents (name, divisionId) VALUES ('Quamar Patterson',5);
INSERT INTO agents (name, divisionId) VALUES ('Alec Foley',7);
INSERT INTO agents (name, divisionId) VALUES ('Jerry Dickerson',5);
INSERT INTO agents (name, divisionId) VALUES ('Kato Howard',1);
INSERT INTO agents (name, divisionId) VALUES ('Christian Glover',16);
INSERT INTO agents (name, divisionId) VALUES ('Griffith Burnett',9);
INSERT INTO agents (name, divisionId) VALUES ('Howard Allen',1);
INSERT INTO agents (name, divisionId) VALUES ('Mannix Horton',6);
INSERT INTO agents (name, divisionId) VALUES ('Beau Beck',13);
INSERT INTO agents (name, divisionId) VALUES ('Xavier Sharpe',18);
INSERT INTO agents (name, divisionId) VALUES ('Ralph Kane',17);
INSERT INTO agents (name, divisionId) VALUES ('Brendan Perry',13);
INSERT INTO agents (name, divisionId) VALUES ('Upton Leach',6);
INSERT INTO agents (name, divisionId) VALUES ('Thane Holder',18);
INSERT INTO agents (name, divisionId) VALUES ('Kennan Parrish',3);
INSERT INTO agents (name, divisionId) VALUES ('William Bird',11);
INSERT INTO agents (name, divisionId) VALUES ('Armand Kennedy',9);
INSERT INTO agents (name, divisionId) VALUES ('Noble Pitts',17);
INSERT INTO agents (name, divisionId) VALUES ('Harlan Cervantes',12);
INSERT INTO agents (name, divisionId) VALUES ('Curran Jackson',10);
INSERT INTO agents (name, divisionId) VALUES ('Tyrone Lopez',13);
INSERT INTO agents (name, divisionId) VALUES ('Ishmael Benson',1);
INSERT INTO agents (name, divisionId) VALUES ('Burke Hartman',18);
INSERT INTO agents (name, divisionId) VALUES ('Eagan Garner',2);
INSERT INTO agents (name, divisionId) VALUES ('Xenos Zamora',3);
INSERT INTO agents (name, divisionId) VALUES ('Edward Marshall',20);
INSERT INTO agents (name, divisionId) VALUES ('Abbot Sharp',13);
INSERT INTO agents (name, divisionId) VALUES ('Salvador Arnold',1);
INSERT INTO agents (name, divisionId) VALUES ('Leroy Lott',18);
INSERT INTO agents (name, divisionId) VALUES ('Roth Estes',20);
INSERT INTO agents (name, divisionId) VALUES ('Cooper Russell',7);
INSERT INTO agents (name, divisionId) VALUES ('Julian Quinn',8);
INSERT INTO agents (name, divisionId) VALUES ('Forrest Osborn',9);
INSERT INTO agents (name, divisionId) VALUES ('Myles Dennis',16);
INSERT INTO agents (name, divisionId) VALUES ('Elmo Wagner',11);
INSERT INTO agents (name, divisionId) VALUES ('Ross Ware',2);
INSERT INTO agents (name, divisionId) VALUES ('Hiram Huff',4);
INSERT INTO agents (name, divisionId) VALUES ('Reece Myers',8);
INSERT INTO agents (name, divisionId) VALUES ('Kato Waller',10);
INSERT INTO agents (name, divisionId) VALUES ('Ivor Lynn',20);
INSERT INTO agents (name, divisionId) VALUES ('Sawyer Ewing',12);
INSERT INTO agents (name, divisionId) VALUES ('Martin Lyons',15);
INSERT INTO agents (name, divisionId) VALUES ('Dexter Maxwell',3);
INSERT INTO agents (name, divisionId) VALUES ('Chaim Cannon',16);
INSERT INTO agents (name, divisionId) VALUES ('Ashton Hunt',12);
INSERT INTO agents (name, divisionId) VALUES ('Ulysses Holland',14);
INSERT INTO agents (name, divisionId) VALUES ('Channing Zamora',10);
INSERT INTO agents (name, divisionId) VALUES ('Travis Harrison',14);
INSERT INTO agents (name, divisionId) VALUES ('Lucius Waters',10);
INSERT INTO agents (name, divisionId) VALUES ('Curran Moss',7);
INSERT INTO agents (name, divisionId) VALUES ('Baker Carey',5);
INSERT INTO agents (name, divisionId) VALUES ('Castor Hartman',20);
INSERT INTO agents (name, divisionId) VALUES ('Carson Macias',20);
INSERT INTO agents (name, divisionId) VALUES ('Herrod Burns',9);
INSERT INTO agents (name, divisionId) VALUES ('Lars Kline',13);
INSERT INTO agents (name, divisionId) VALUES ('Jelani Mcfarland',11);
INSERT INTO agents (name, divisionId) VALUES ('Rajah Madden',18);
INSERT INTO agents (name, divisionId) VALUES ('Josiah Oneil',11);
INSERT INTO agents (name, divisionId) VALUES ('Ferdinand Burnett',9);
INSERT INTO agents (name, divisionId) VALUES ('Randall Ball',13);
INSERT INTO agents (name, divisionId) VALUES ('Kaseem Alvarado',5);
INSERT INTO agents (name, divisionId) VALUES ('Fuller Mckay',18);
INSERT INTO agents (name, divisionId) VALUES ('Hilel Morales',14);
INSERT INTO agents (name, divisionId) VALUES ('Zahir Blackburn',1);
INSERT INTO agents (name, divisionId) VALUES ('Jason Everett',19);
INSERT INTO agents (name, divisionId) VALUES ('Dominic Beck',6);
INSERT INTO agents (name, divisionId) VALUES ('Burton Bridges',10);
INSERT INTO agents (name, divisionId) VALUES ('Thomas Hanson',18);

INSERT INTO incomings (agentId, value) VALUES (10,817);
INSERT INTO incomings (agentId, value) VALUES (3,586);
INSERT INTO incomings (agentId, value) VALUES (6,539);
INSERT INTO incomings (agentId, value) VALUES (14,831);
INSERT INTO incomings (agentId, value) VALUES (19,365);
INSERT INTO incomings (agentId, value) VALUES (4,584);
INSERT INTO incomings (agentId, value) VALUES (3,791);
INSERT INTO incomings (agentId, value) VALUES (10,525);
INSERT INTO incomings (agentId, value) VALUES (2,410);
INSERT INTO incomings (agentId, value) VALUES (1,49);
INSERT INTO incomings (agentId, value) VALUES (20,436);
INSERT INTO incomings (agentId, value) VALUES (11,923);
INSERT INTO incomings (agentId, value) VALUES (9,795);
INSERT INTO incomings (agentId, value) VALUES (12,396);
INSERT INTO incomings (agentId, value) VALUES (20,83);
INSERT INTO incomings (agentId, value) VALUES (13,329);
INSERT INTO incomings (agentId, value) VALUES (20,522);
INSERT INTO incomings (agentId, value) VALUES (9,272);
INSERT INTO incomings (agentId, value) VALUES (13,492);
INSERT INTO incomings (agentId, value) VALUES (10,61);
INSERT INTO incomings (agentId, value) VALUES (5,911);
INSERT INTO incomings (agentId, value) VALUES (6,18);
INSERT INTO incomings (agentId, value) VALUES (16,716);
INSERT INTO incomings (agentId, value) VALUES (15,550);
INSERT INTO incomings (agentId, value) VALUES (18,224);
INSERT INTO incomings (agentId, value) VALUES (6,204);
INSERT INTO incomings (agentId, value) VALUES (16,602);
INSERT INTO incomings (agentId, value) VALUES (13,102);
INSERT INTO incomings (agentId, value) VALUES (8,604);
INSERT INTO incomings (agentId, value) VALUES (5,391);
INSERT INTO incomings (agentId, value) VALUES (18,334);
INSERT INTO incomings (agentId, value) VALUES (17,281);
INSERT INTO incomings (agentId, value) VALUES (4,369);
INSERT INTO incomings (agentId, value) VALUES (6,395);
INSERT INTO incomings (agentId, value) VALUES (2,204);
INSERT INTO incomings (agentId, value) VALUES (8,630);
INSERT INTO incomings (agentId, value) VALUES (14,228);
INSERT INTO incomings (agentId, value) VALUES (11,179);
INSERT INTO incomings (agentId, value) VALUES (20,169);
INSERT INTO incomings (agentId, value) VALUES (13,672);
INSERT INTO incomings (agentId, value) VALUES (11,18);
INSERT INTO incomings (agentId, value) VALUES (19,391);
INSERT INTO incomings (agentId, value) VALUES (19,386);
INSERT INTO incomings (agentId, value) VALUES (6,328);
INSERT INTO incomings (agentId, value) VALUES (2,616);
INSERT INTO incomings (agentId, value) VALUES (17,930);
INSERT INTO incomings (agentId, value) VALUES (16,321);
INSERT INTO incomings (agentId, value) VALUES (8,769);
INSERT INTO incomings (agentId, value) VALUES (6,669);
INSERT INTO incomings (agentId, value) VALUES (4,590);
INSERT INTO incomings (agentId, value) VALUES (10,55);
INSERT INTO incomings (agentId, value) VALUES (9,5);
INSERT INTO incomings (agentId, value) VALUES (3,689);
INSERT INTO incomings (agentId, value) VALUES (4,25);
INSERT INTO incomings (agentId, value) VALUES (17,670);
INSERT INTO incomings (agentId, value) VALUES (13,856);
INSERT INTO incomings (agentId, value) VALUES (9,392);
INSERT INTO incomings (agentId, value) VALUES (6,831);
INSERT INTO incomings (agentId, value) VALUES (7,516);
INSERT INTO incomings (agentId, value) VALUES (7,442);
INSERT INTO incomings (agentId, value) VALUES (2,608);
INSERT INTO incomings (agentId, value) VALUES (1,748);
INSERT INTO incomings (agentId, value) VALUES (10,732);
INSERT INTO incomings (agentId, value) VALUES (7,430);
INSERT INTO incomings (agentId, value) VALUES (2,286);
INSERT INTO incomings (agentId, value) VALUES (3,633);
INSERT INTO incomings (agentId, value) VALUES (16,872);
INSERT INTO incomings (agentId, value) VALUES (17,140);
INSERT INTO incomings (agentId, value) VALUES (2,700);
INSERT INTO incomings (agentId, value) VALUES (8,667);
INSERT INTO incomings (agentId, value) VALUES (12,741);
INSERT INTO incomings (agentId, value) VALUES (11,621);
INSERT INTO incomings (agentId, value) VALUES (13,732);
INSERT INTO incomings (agentId, value) VALUES (6,74);
INSERT INTO incomings (agentId, value) VALUES (9,412);
INSERT INTO incomings (agentId, value) VALUES (6,914);
INSERT INTO incomings (agentId, value) VALUES (19,106);
INSERT INTO incomings (agentId, value) VALUES (17,263);
INSERT INTO incomings (agentId, value) VALUES (5,670);
INSERT INTO incomings (agentId, value) VALUES (16,551);
INSERT INTO incomings (agentId, value) VALUES (1,42);
INSERT INTO incomings (agentId, value) VALUES (2,239);
INSERT INTO incomings (agentId, value) VALUES (3,889);
INSERT INTO incomings (agentId, value) VALUES (17,820);
INSERT INTO incomings (agentId, value) VALUES (8,581);
INSERT INTO incomings (agentId, value) VALUES (3,123);
INSERT INTO incomings (agentId, value) VALUES (17,309);
INSERT INTO incomings (agentId, value) VALUES (19,82);
INSERT INTO incomings (agentId, value) VALUES (14,931);
INSERT INTO incomings (agentId, value) VALUES (11,116);
INSERT INTO incomings (agentId, value) VALUES (20,338);
INSERT INTO incomings (agentId, value) VALUES (16,238);
INSERT INTO incomings (agentId, value) VALUES (2,272);
INSERT INTO incomings (agentId, value) VALUES (19,286);
INSERT INTO incomings (agentId, value) VALUES (2,793);
INSERT INTO incomings (agentId, value) VALUES (8,549);
INSERT INTO incomings (agentId, value) VALUES (7,39);
INSERT INTO incomings (agentId, value) VALUES (14,143);
INSERT INTO incomings (agentId, value) VALUES (2,880);
INSERT INTO incomings (agentId, value) VALUES (2,842);

INSERT INTO incomings (agentId, value) VALUES (7,199);
INSERT INTO incomings (agentId, value) VALUES (7,621);
INSERT INTO incomings (agentId, value) VALUES (16,842);
INSERT INTO incomings (agentId, value) VALUES (17,521);
INSERT INTO incomings (agentId, value) VALUES (18,242);
INSERT INTO incomings (agentId, value) VALUES (13,70);
INSERT INTO incomings (agentId, value) VALUES (17,226);
INSERT INTO incomings (agentId, value) VALUES (17,867);
INSERT INTO incomings (agentId, value) VALUES (18,637);
INSERT INTO incomings (agentId, value) VALUES (17,393);
INSERT INTO incomings (agentId, value) VALUES (2,1000);
INSERT INTO incomings (agentId, value) VALUES (12,581);
INSERT INTO incomings (agentId, value) VALUES (16,942);
INSERT INTO incomings (agentId, value) VALUES (11,326);
INSERT INTO incomings (agentId, value) VALUES (19,639);
INSERT INTO incomings (agentId, value) VALUES (16,740);
INSERT INTO incomings (agentId, value) VALUES (18,363);
INSERT INTO incomings (agentId, value) VALUES (6,951);
INSERT INTO incomings (agentId, value) VALUES (7,805);
INSERT INTO incomings (agentId, value) VALUES (16,398);
INSERT INTO incomings (agentId, value) VALUES (15,548);
INSERT INTO incomings (agentId, value) VALUES (19,352);
INSERT INTO incomings (agentId, value) VALUES (18,204);
INSERT INTO incomings (agentId, value) VALUES (5,104);
INSERT INTO incomings (agentId, value) VALUES (10,719);
INSERT INTO incomings (agentId, value) VALUES (6,881);
INSERT INTO incomings (agentId, value) VALUES (9,925);
INSERT INTO incomings (agentId, value) VALUES (4,296);
INSERT INTO incomings (agentId, value) VALUES (3,849);
INSERT INTO incomings (agentId, value) VALUES (17,968);
INSERT INTO incomings (agentId, value) VALUES (8,210);
INSERT INTO incomings (agentId, value) VALUES (4,346);
INSERT INTO incomings (agentId, value) VALUES (17,825);
INSERT INTO incomings (agentId, value) VALUES (5,232);
INSERT INTO incomings (agentId, value) VALUES (5,774);
INSERT INTO incomings (agentId, value) VALUES (15,120);
INSERT INTO incomings (agentId, value) VALUES (6,312);
INSERT INTO incomings (agentId, value) VALUES (2,521);
INSERT INTO incomings (agentId, value) VALUES (6,894);
INSERT INTO incomings (agentId, value) VALUES (11,112);
INSERT INTO incomings (agentId, value) VALUES (7,27);
INSERT INTO incomings (agentId, value) VALUES (17,603);
INSERT INTO incomings (agentId, value) VALUES (7,688);
INSERT INTO incomings (agentId, value) VALUES (14,582);
INSERT INTO incomings (agentId, value) VALUES (5,546);
INSERT INTO incomings (agentId, value) VALUES (1,535);
INSERT INTO incomings (agentId, value) VALUES (20,819);
INSERT INTO incomings (agentId, value) VALUES (8,881);
INSERT INTO incomings (agentId, value) VALUES (11,649);
INSERT INTO incomings (agentId, value) VALUES (18,382);
INSERT INTO incomings (agentId, value) VALUES (2,703);
INSERT INTO incomings (agentId, value) VALUES (6,850);
INSERT INTO incomings (agentId, value) VALUES (15,170);
INSERT INTO incomings (agentId, value) VALUES (13,289);
INSERT INTO incomings (agentId, value) VALUES (14,938);
INSERT INTO incomings (agentId, value) VALUES (13,524);
INSERT INTO incomings (agentId, value) VALUES (16,127);
INSERT INTO incomings (agentId, value) VALUES (17,688);
INSERT INTO incomings (agentId, value) VALUES (8,834);
INSERT INTO incomings (agentId, value) VALUES (1,986);
INSERT INTO incomings (agentId, value) VALUES (6,800);
INSERT INTO incomings (agentId, value) VALUES (12,689);
INSERT INTO incomings (agentId, value) VALUES (4,157);
INSERT INTO incomings (agentId, value) VALUES (12,850);
INSERT INTO incomings (agentId, value) VALUES (1,931);
INSERT INTO incomings (agentId, value) VALUES (6,263);
INSERT INTO incomings (agentId, value) VALUES (15,970);
INSERT INTO incomings (agentId, value) VALUES (15,75);
INSERT INTO incomings (agentId, value) VALUES (12,27);
INSERT INTO incomings (agentId, value) VALUES (4,259);
INSERT INTO incomings (agentId, value) VALUES (20,494);
INSERT INTO incomings (agentId, value) VALUES (13,937);
INSERT INTO incomings (agentId, value) VALUES (15,153);
INSERT INTO incomings (agentId, value) VALUES (19,282);
INSERT INTO incomings (agentId, value) VALUES (7,552);
INSERT INTO incomings (agentId, value) VALUES (7,310);
INSERT INTO incomings (agentId, value) VALUES (6,648);
INSERT INTO incomings (agentId, value) VALUES (14,31);
INSERT INTO incomings (agentId, value) VALUES (17,687);
INSERT INTO incomings (agentId, value) VALUES (14,810);
INSERT INTO incomings (agentId, value) VALUES (15,122);
INSERT INTO incomings (agentId, value) VALUES (4,110);
INSERT INTO incomings (agentId, value) VALUES (14,629);
INSERT INTO incomings (agentId, value) VALUES (8,30);
INSERT INTO incomings (agentId, value) VALUES (12,787);
INSERT INTO incomings (agentId, value) VALUES (15,656);
INSERT INTO incomings (agentId, value) VALUES (5,488);
INSERT INTO incomings (agentId, value) VALUES (7,229);
INSERT INTO incomings (agentId, value) VALUES (6,128);
INSERT INTO incomings (agentId, value) VALUES (9,775);
INSERT INTO incomings (agentId, value) VALUES (13,241);
INSERT INTO incomings (agentId, value) VALUES (20,228);
INSERT INTO incomings (agentId, value) VALUES (5,900);
INSERT INTO incomings (agentId, value) VALUES (19,767);
INSERT INTO incomings (agentId, value) VALUES (13,321);
INSERT INTO incomings (agentId, value) VALUES (18,680);
INSERT INTO incomings (agentId, value) VALUES (4,429);
INSERT INTO incomings (agentId, value) VALUES (17,281);
INSERT INTO incomings (agentId, value) VALUES (4,608);
INSERT INTO incomings (agentId, value) VALUES (19,276);

INSERT INTO incomings (agentId, value) VALUES (5,483);
INSERT INTO incomings (agentId, value) VALUES (20,878);
INSERT INTO incomings (agentId, value) VALUES (17,572);
INSERT INTO incomings (agentId, value) VALUES (2,824);
INSERT INTO incomings (agentId, value) VALUES (20,632);
INSERT INTO incomings (agentId, value) VALUES (17,759);
INSERT INTO incomings (agentId, value) VALUES (10,431);
INSERT INTO incomings (agentId, value) VALUES (11,936);
INSERT INTO incomings (agentId, value) VALUES (15,468);
INSERT INTO incomings (agentId, value) VALUES (9,162);
INSERT INTO incomings (agentId, value) VALUES (10,985);
INSERT INTO incomings (agentId, value) VALUES (19,894);
INSERT INTO incomings (agentId, value) VALUES (8,262);
INSERT INTO incomings (agentId, value) VALUES (16,732);
INSERT INTO incomings (agentId, value) VALUES (18,127);
INSERT INTO incomings (agentId, value) VALUES (10,66);
INSERT INTO incomings (agentId, value) VALUES (1,787);
INSERT INTO incomings (agentId, value) VALUES (7,859);
INSERT INTO incomings (agentId, value) VALUES (18,467);
INSERT INTO incomings (agentId, value) VALUES (20,434);
INSERT INTO incomings (agentId, value) VALUES (12,301);
INSERT INTO incomings (agentId, value) VALUES (6,448);
INSERT INTO incomings (agentId, value) VALUES (4,57);
INSERT INTO incomings (agentId, value) VALUES (6,223);
INSERT INTO incomings (agentId, value) VALUES (9,4);
INSERT INTO incomings (agentId, value) VALUES (8,784);
INSERT INTO incomings (agentId, value) VALUES (8,308);
INSERT INTO incomings (agentId, value) VALUES (18,307);
INSERT INTO incomings (agentId, value) VALUES (5,432);
INSERT INTO incomings (agentId, value) VALUES (3,696);
INSERT INTO incomings (agentId, value) VALUES (1,479);
INSERT INTO incomings (agentId, value) VALUES (8,132);
INSERT INTO incomings (agentId, value) VALUES (2,579);
INSERT INTO incomings (agentId, value) VALUES (10,958);
INSERT INTO incomings (agentId, value) VALUES (16,112);
INSERT INTO incomings (agentId, value) VALUES (15,733);
INSERT INTO incomings (agentId, value) VALUES (2,882);
INSERT INTO incomings (agentId, value) VALUES (14,162);
INSERT INTO incomings (agentId, value) VALUES (1,309);
INSERT INTO incomings (agentId, value) VALUES (19,325);
INSERT INTO incomings (agentId, value) VALUES (16,23);
INSERT INTO incomings (agentId, value) VALUES (17,89);
INSERT INTO incomings (agentId, value) VALUES (5,775);
INSERT INTO incomings (agentId, value) VALUES (3,110);
INSERT INTO incomings (agentId, value) VALUES (18,434);
INSERT INTO incomings (agentId, value) VALUES (2,962);
INSERT INTO incomings (agentId, value) VALUES (19,808);
INSERT INTO incomings (agentId, value) VALUES (4,182);
INSERT INTO incomings (agentId, value) VALUES (15,947);
INSERT INTO incomings (agentId, value) VALUES (4,680);
INSERT INTO incomings (agentId, value) VALUES (1,918);
INSERT INTO incomings (agentId, value) VALUES (19,544);
INSERT INTO incomings (agentId, value) VALUES (14,372);
INSERT INTO incomings (agentId, value) VALUES (19,975);
INSERT INTO incomings (agentId, value) VALUES (4,390);
INSERT INTO incomings (agentId, value) VALUES (11,733);
INSERT INTO incomings (agentId, value) VALUES (18,34);
INSERT INTO incomings (agentId, value) VALUES (14,948);
INSERT INTO incomings (agentId, value) VALUES (14,631);
INSERT INTO incomings (agentId, value) VALUES (16,892);
INSERT INTO incomings (agentId, value) VALUES (4,34);
INSERT INTO incomings (agentId, value) VALUES (6,186);
INSERT INTO incomings (agentId, value) VALUES (17,668);
INSERT INTO incomings (agentId, value) VALUES (15,680);
INSERT INTO incomings (agentId, value) VALUES (9,798);
INSERT INTO incomings (agentId, value) VALUES (16,51);
INSERT INTO incomings (agentId, value) VALUES (3,231);
INSERT INTO incomings (agentId, value) VALUES (16,29);
INSERT INTO incomings (agentId, value) VALUES (7,967);
INSERT INTO incomings (agentId, value) VALUES (9,100);
INSERT INTO incomings (agentId, value) VALUES (19,147);
INSERT INTO incomings (agentId, value) VALUES (5,973);
INSERT INTO incomings (agentId, value) VALUES (11,848);
INSERT INTO incomings (agentId, value) VALUES (13,392);
INSERT INTO incomings (agentId, value) VALUES (11,466);
INSERT INTO incomings (agentId, value) VALUES (5,155);
INSERT INTO incomings (agentId, value) VALUES (18,989);
INSERT INTO incomings (agentId, value) VALUES (1,325);
INSERT INTO incomings (agentId, value) VALUES (6,3);
INSERT INTO incomings (agentId, value) VALUES (15,882);
INSERT INTO incomings (agentId, value) VALUES (5,163);
INSERT INTO incomings (agentId, value) VALUES (9,906);
INSERT INTO incomings (agentId, value) VALUES (8,177);
INSERT INTO incomings (agentId, value) VALUES (7,755);
INSERT INTO incomings (agentId, value) VALUES (20,802);
INSERT INTO incomings (agentId, value) VALUES (14,915);
INSERT INTO incomings (agentId, value) VALUES (13,226);
INSERT INTO incomings (agentId, value) VALUES (11,154);
INSERT INTO incomings (agentId, value) VALUES (11,153);
INSERT INTO incomings (agentId, value) VALUES (19,679);
INSERT INTO incomings (agentId, value) VALUES (4,26);
INSERT INTO incomings (agentId, value) VALUES (18,232);
INSERT INTO incomings (agentId, value) VALUES (16,932);
INSERT INTO incomings (agentId, value) VALUES (5,987);
INSERT INTO incomings (agentId, value) VALUES (15,406);
INSERT INTO incomings (agentId, value) VALUES (15,457);
INSERT INTO incomings (agentId, value) VALUES (3,776);
INSERT INTO incomings (agentId, value) VALUES (16,783);
INSERT INTO incomings (agentId, value) VALUES (1,474);
INSERT INTO incomings (agentId, value) VALUES (6,954);

INSERT INTO divisions (name) VALUES ('Ultricies Dignissim Incorporated');
INSERT INTO divisions (name) VALUES ('Nec LLC');
INSERT INTO divisions (name) VALUES ('Nisi Consulting');
INSERT INTO divisions (name) VALUES ('Aliquet Sem Ut Foundation');
INSERT INTO divisions (name) VALUES ('Massa Suspendisse Eleifend Inc.');
INSERT INTO divisions (name) VALUES ('Mi Eleifend Egestas Foundation');
INSERT INTO divisions (name) VALUES ('Dui Augue Eu Foundation');
INSERT INTO divisions (name) VALUES ('Non LLC');
INSERT INTO divisions (name) VALUES ('Nunc Ullamcorper Inc.');
INSERT INTO divisions (name) VALUES ('In Tincidunt Inc.');
INSERT INTO divisions (name) VALUES ('Cubilia Institute');
INSERT INTO divisions (name) VALUES ('Proin Velit Sed Ltd');
INSERT INTO divisions (name) VALUES ('Ac Inc.');
INSERT INTO divisions (name) VALUES ('Tristique Senectus Et Industries');
INSERT INTO divisions (name) VALUES ('Et Rutrum Industries');
INSERT INTO divisions (name) VALUES ('Risus Nulla Eget Associates');
INSERT INTO divisions (name) VALUES ('Est Nunc Company');
INSERT INTO divisions (name) VALUES ('Enim Sed Company');
INSERT INTO divisions (name) VALUES ('Lorem Donec Elementum LLC');
INSERT INTO divisions (name) VALUES ('Tellus Suspendisse Corporation');
INSERT INTO divisions (name) VALUES ('Orci Lacus Corp.');
INSERT INTO divisions (name) VALUES ('Sed Associates');
INSERT INTO divisions (name) VALUES ('In Faucibus Ltd');
INSERT INTO divisions (name) VALUES ('Molestie Arcu Industries');
INSERT INTO divisions (name) VALUES ('Nibh Enim Gravida Industries');
INSERT INTO divisions (name) VALUES ('Rhoncus LLC');
INSERT INTO divisions (name) VALUES ('Id Mollis Industries');
INSERT INTO divisions (name) VALUES ('Euismod Inc.');
INSERT INTO divisions (name) VALUES ('Donec Felis Orci Industries');
